package com.ligicate.algo.markets;

public interface Markets {
	public static final String CUSTODIAL_MARKET_ADDRESS = "JQAJLW25IM42QDYIABHZEHMSWKGY3TV2J6XJWWH5BTRMCHO42L5P7QXQCI";
	
	public static final String LOAN_MARKET_ADDRESS 		= "ZZ3NUXTCTOZSZK7VAVCGRWFEFIIBBEM7BOH3BBNEAJW2NLSFQQZIRKFOPA";
	
	public static final String MONEY_MANAGER_ADDRESS	= "7A2C5ATF3OH7IIV5FSGMADTH6PMCQ74XT5WQII242KYY2II2UHS6RWSHXM";
}
